<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ05BPMj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ05BPMj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ05BPMj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ05BPMj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZ05BPMj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Z05BPMj',
    'container.build_id' => '2b3407a6',
    'container.build_time' => 1651965762,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ05BPMj');
