<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKiHymHu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKiHymHu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKiHymHu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKiHymHu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKiHymHu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KiHymHu',
    'container.build_id' => '55e6c8d0',
    'container.build_time' => 1652355954,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKiHymHu');
